name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: 
        nuget sources add -name "github" -source https://nuget.pkg.github.com/rcangus/index.json -StorePasswordInClearText -username rcangus -password ${{ secrets.PACKAGES_PAT }}
        dotnet restore source/TSC.Composition.Services.Shared/TSC.Composition.Services.Shared.csproj
    - name: Build
      run: dotnet build source/TSC.Composition.Services.Shared/TSC.Composition.Services.Shared.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test source/TSC.Composition.Services.Shared/TSC.Composition.Services.Shared.csproj --no-restore --verbosity normal
